apiVersion: apps/v1
kind: Deployment
metadata:
  name: fedml-agent-device-id1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fedml-agent-device-id1
  template:
    metadata:
      labels:
        app: fedml-agent-device-id1
    spec:
      nodeName: edge-dgx-134
      dnsConfig:
        nameservers:
          - 8.8.8.8
      containers:
      # fedml-agent is the fix container name that runs the fedml(master&slave)
      - name: fedml-agent
        image: fedml/fedml-k8s-agent:202501061430
        imagePullPolicy: IfNotPresent
        env:
        - name: SCHEDULER_TYPE
          value: "K8S"
        - name: FEDML_API_KEY
          value: "de6aa755c9114534a9805dce8c702355"
        - name: FEDML_ENV
          value: "test"
        - name: FEDML_PROVIDER
          value: "false"
        - name: FEDML_DEVICE_ID
          value: "edge-dgx-134-000002"
        resources:
          requests:
            nvidia.com/gpu: 2
            cpu: "8"
            memory: "32Gi"
          limits:
            nvidia.com/gpu: 2
            cpu: "8"
            memory: "32Gi"