common_args:
  training_type: "cross_silo"
  scenario: "horizontal"
  using_mlops: false
  random_seed: 0
  config_version: release

environment_args:
  bootstrap: config/bootstrap.sh

data_args:
  dataset: "femnist"
  data_cache_dir: ~/../../data/shanshan/federatedEMNIST
  partition_method: "hetero"
  partition_alpha: 0.5

model_args:
  model: "cnn"
  model_file_cache_folder: "./model_file_cache" # will be filled by the server automatically
  global_model_file_path: "./model_file_cache/global_model.pt"

train_args:
  federated_optimizer: "FedAvg"
  # for CLI running, this can be None; in MLOps deployment, `client_id_list` will be replaced with real-time selected devices
  client_id_list:
  # for FoolsGold Defense, if use_memory is true, then client_num_in_total should be equal to client_number_per_round
  client_num_in_total: 10
  client_num_per_round: 10
  comm_round: 100
  epochs: 1
  batch_size: 10
  client_optimizer: sgd
  learning_rate: 0.03
  weight_decay: 0.001

validation_args:
  frequency_of_the_test: 1

device_args:
  worker_num: 10
  using_gpu: true
  gpu_mapping_file: config/gpu_mapping.yaml
  gpu_mapping_key: mapping_default

comm_args:
  backend: "MPI"

tracking_args:
   # When running on MLOps platform(open.fedml.ai), the default log path is at ~/.fedml/fedml-client/fedml/logs/ and ~/.fedml/fedml-server/fedml/logs/
  enable_wandb: false
  wandb_key: bf0149e33cec3bcb7833c43aa5bd6e74f9dbedaf
  wandb_project: FedmlSecurity
  wandb_name: hetero_mnist_byzantine_random_1adv
  
attack_args:
  enable_attack: true
  attack_type: byzantine
  byzantine_client_num: 1
  attack_mode: random