MSG_TYPE_CONNECTION_IS_READY = 0
MSG_TYPE_NEIGHBOR_CHECK_NODE_STATUS = "MSG_TYPE_NEIGHBOR_CHECK_NODE_STATUS"
MSG_TYPE_NEIGHBOR_REPORT_NODE_STATUS = "MSG_TYPE_NEIGHBOR_REPORT_NODE_STATUS"
MSG_TYPE_FLOW_FINISH = "MSG_TYPE_FLOW_FINISH"

MSG_ARG_KEY_TYPE = "msg_type"

PARAMS_KEY_SENDER_ID = "sender_id"
PARAMS_KEY_RECEIVER_ID = "receiver_id"