# this is used for 4 clients and 1 server training within a single machine which has 8 GPUs, but you hope to skip the GPU device ID.
mapping_default:
  host1: [3, 2, 2, 2]  # assume we only have 4 GPUs