ARG VERSION=dev
ARG IS_BUILDING_GPU_IMAGE=0
ARG BASE_IMAGE=continuumio/miniconda3:4.7.12
FROM ${BASE_IMAGE}

ADD ./devops/scripts/requirements.txt ./
ADD ./devops/scripts/setup-conda-env.sh ./
ADD ./devops/scripts/copy-fedml-package.sh ./

RUN chmod a+x ./setup-conda-env.sh
RUN bash ./setup-conda-env.sh ${IS_BUILDING_GPU_IMAGE}
RUN pip install --upgrade pip
RUN pip3 uninstall fedml
RUN pip3 install fedml
RUN pip3 install -r ./requirements.txt

COPY ./python/fedml ./fedml-pip
RUN chmod a+x ./copy-fedml-package.sh
RUN bash ./copy-fedml-package.sh

WORKDIR ./fedml

ENV MODE=normal FEDML_VERSION=${VERSION} \
    FEDML_PACKAGE_NAME=package FEDML_PACKAGE_URL=s3_url \
    FEDML_RUNNER_CMD={}

CMD fedml login 0 -v dev -s -lm cloud_server -rc ${FEDML_RUNNER_CMD}
