FROM fedml/fedml:cuda-11.4.0-devel-ubuntu20.04
COPY ./python/fedml ./fedml-pip
COPY ./devops/fedml/conf/fedml.yaml ./fedml/conf/fedml.yaml
COPY ./devops/fedml/main.py ./fedml/main.py
WORKDIR ./fedml

ENV MODE=normal FEDML_VERSION=${VERSION} \
    FEDML_PACKAGE_NAME=package FEDML_PACKAGE_URL=s3_url

CMD sh -c "cp -Rf /fedml-pip/* `python3 -c 'import sysconfig; print(sysconfig.get_paths()["purelib"])'`/fedml";python ./main.py --mode=${MODE} --version={FEDML_VERSION} \
    --package_name=${FEDML_PACKAGE_NAME} --package_url=${FEDML_PACKAGE_URL}
