workspace: "./src"
entry_point: "inference_entry.py"
bootstrap: |
  echo "Bootstrap start..."
  sh bootstrap.sh
  echo "Bootstrap finished"
inference_image_name: "fedml/stable-diffusion"
use_gpu: true
request_input_example: {"text": "Lovely Flowers"}
data_cache_dir: "/data/scalellm_share_dir"
deploy_timeout: 1000
auto_detect_public_ip: true
environment_variables:
  LOCAL_ROOT: "/data/scalellm_share_dir"

# computing:
#   minimum_num_gpus: 1           # minimum # of GPUs to provision
#   maximum_cost_per_hour: $3000   # max cost per hour for your job per gpu card
#   resource_type: A100-80G       # e.g., A100-80G,
#   #allow_cross_cloud_resources: true # true, false
#   #device_type: CPU              # options: GPU, CPU, hybrid
