ARG VERSION=base
ARG IS_BUILDING_GPU_IMAGE=0
#ARG BASE_IMAGE=continuumio/miniconda3:4.7.12
ARG BASE_IMAGE=docker.io/fedml/fedml:latest-torch1.13.1-cuda11.6-cudnn8-devel
FROM ${BASE_IMAGE}

ADD ./devops/scripts/aws ./fedml/aws
ADD ./devops/scripts/setup-aws-cli.sh ./fedml/setup-aws-cli.sh
ADD ./devops/scripts/set-aws-credentials.sh ./fedml/set-aws-credentials.sh
ADD ./devops/scripts/docker /usr/bin/
ADD ./devops/scripts/kubectl /usr/bin/
ADD ./devops/scripts/start-redis.sh ./fedml/start-redis.sh

ADD ./devops/scripts/requirements.txt ./fedml/requirements.txt
ADD ./devops/scripts/setup-conda-env.sh ./fedml/setup-conda-env.sh

RUN chmod a+x /usr/bin/docker
RUN chmod a+x /usr/bin/kubectl
RUN chmod a+x ./fedml/setup-aws-cli.sh
RUN chmod a+x ./fedml/set-aws-credentials.sh
RUN ./fedml/setup-aws-cli.sh

RUN curl -fsSL https://packages.redis.io/gpg | sudo gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg
RUN echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/redis.list
RUN apt-get -y update
RUN apt-get install -y redis

#RUN apt-get -y install gettext-base
#RUN apt-get -y install unar wget
#RUN apt-get -y install libquadmath0

RUN sudo DEBIAN_FRONTEND=noninteractive apt-get install -qq gettext-base < /dev/null > /dev/null
RUN sudo DEBIAN_FRONTEND=noninteractive apt-get install -qq unar wget < /dev/null > /dev/null
RUN sudo DEBIAN_FRONTEND=noninteractive apt-get install -qq libquadmath0 < /dev/null > /dev/null

RUN chmod a+x ./fedml/setup-conda-env.sh
RUN bash ./fedml/setup-conda-env.sh ${IS_BUILDING_GPU_IMAGE}

#RUN pip install --upgrade pip
#RUN pip3 uninstall fedml

RUN pip3 install --upgrade fedml
RUN pip3 install -r ./fedml/requirements.txt
RUN pip3 install --upgrade gevent

