workspace: "."
entry_point: "main_entry.py"

auto_detect_public_ip: true
server_external_port: 10007
server_internal_port: 10008

bootstrap: |
  echo "Bootstrap start..."
  pip install -U fedml
  python3 /home/fedml/models_serving/main_entry.py
  echo "Bootstrap finished"

inference_image_name: "ccr-23gxup9u-pub.cnc.bj.baidubce.com/public/mv2model:v1"
enable_custom_image: true
use_gpu: true
deploy_timeout: 1800