# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import grpc_comm_manager_stream_pb2 as grpc__comm__manager__stream__pb2


class GRPCCommManagerStreamStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.unary_stream(
                '/GRPCCommManagerStream/Connect',
                request_serializer=grpc__comm__manager__stream__pb2.ConnectRequest.SerializeToString,
                response_deserializer=grpc__comm__manager__stream__pb2.CommRequest.FromString,
                )
        self.SendToServer = channel.unary_unary(
                '/GRPCCommManagerStream/SendToServer',
                request_serializer=grpc__comm__manager__stream__pb2.CommRequest.SerializeToString,
                response_deserializer=grpc__comm__manager__stream__pb2.Empty.FromString,
                )


class GRPCCommManagerStreamServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Connect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendToServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GRPCCommManagerStreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.unary_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=grpc__comm__manager__stream__pb2.ConnectRequest.FromString,
                    response_serializer=grpc__comm__manager__stream__pb2.CommRequest.SerializeToString,
            ),
            'SendToServer': grpc.unary_unary_rpc_method_handler(
                    servicer.SendToServer,
                    request_deserializer=grpc__comm__manager__stream__pb2.CommRequest.FromString,
                    response_serializer=grpc__comm__manager__stream__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GRPCCommManagerStream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GRPCCommManagerStream(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/GRPCCommManagerStream/Connect',
            grpc__comm__manager__stream__pb2.ConnectRequest.SerializeToString,
            grpc__comm__manager__stream__pb2.CommRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendToServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCCommManagerStream/SendToServer',
            grpc__comm__manager__stream__pb2.CommRequest.SerializeToString,
            grpc__comm__manager__stream__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
