export class ClientConstants {
  static MSG_MLOPS_CLIENT_STATUS_OFFLINE = 'OFFLINE';
  static MSG_MLOPS_CLIENT_STATUS_IDLE = 'IDLE';
  static MSG_MLOPS_CLIENT_STATUS_UPGRADING = 'UPGRADING';
  static MSG_MLOPS_CLIENT_STATUS_QUEUED = 'QUEUED';
  static MSG_MLOPS_CLIENT_STATUS_INITIALIZING = 'INITIALIZING';
  static MSG_MLOPS_CLIENT_STATUS_TRAINING = 'TRAINING';
  static MSG_MLOPS_CLIENT_STATUS_FAILED = 'FAILED';
  static MSG_MLOPS_CLIENT_STATUS_FINISHED = 'FINISHED';

  static MSG_MLOPS_SERVER_DEVICE_STATUS_OFFLINE = 'OFFLINE';
  static MSG_MLOPS_SERVER_DEVICE_STATUS_IDLE = 'IDLE';
  static MSG_MLOPS_SERVER_DEVICE_STATUS_STARTING = 'STARTING';
  static MSG_MLOPS_SERVER_DEVICE_STATUS_RUNNING = 'RUNNING';
  static MSG_MLOPS_SERVER_DEVICE_STATUS_FAILED = 'FAILED';
  static MSG_MLOPS_SERVER_DEVICE_STATUS_FINISHED = 'FINISHED';

  static LOCAL_HOME_RUNNER_DIR_NAME = 'fedml-client';
  static LOCAL_RUNNER_INFO_DIR_NAME = 'runner_infos';
  static LOCAL_PACKAGE_HOME_DIR_NAME = 'fedml_packages';

  static FEDML_OTA_CMD_UPGRADE = 'upgrade';
  static FEDML_OTA_CMD_RESTART = 'restart';

  static LOGIN_MODE_CLIEN_INDEX = 0;
  static LOGIN_MODE_EDGE_SIMULATOR_INDEX = 1;
  static login_role_list = ['client', 'edge_simulator'];
}
