kind: Service
apiVersion: v1
metadata:
  labels:
    name: redis
  name: fedml-redis
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    name: redis