common_args:
  training_type: "cross_silo"
  scenario: "horizontal"
  using_mlops: false
  random_seed: 0

environment_args:
  bootstrap: config/bootstrap.sh

data_args:
  dataset: "Brain tumor segmentation"
  data_cache_dir: "./content/data/slices"
  preprocessed: true
  partition_method: "hetero"
  partition_alpha: 0.5

model_args:
  model: "Res2D_Unet"
  input_dim: 256
  input_channels: 3
  output_dim: 6
  model_file_cache_folder: "./model_file_cache" # will be filled by the server automatically
  global_model_file_path: "./model_file_cache/global_model.pt"

train_args:
  ml_engine: "tf"
  federated_optimizer: "FedAvg"
  client_id_list:
  client_num_in_total: 1
  client_num_per_round: 1
  comm_round: 2
  epochs: 1
  batch_size: 3
  client_optimizer: adam
  learning_rate: 0.0001
  weight_decay: 0.001

validation_args:
  frequency_of_the_test: 1

device_args:
  device_type: "gpu"
  worker_num: 1
  using_gpu: false
  gpu_id: 0

comm_args:
  backend: "MQTT_S3"
  mqtt_config_path: config/mqtt_config.yaml
  s3_config_path: config/s3_config.yaml

tracking_args:
  log_file_dir: ./log
  enable_wandb: false
  wandb_key: ee0b5f53d949c84cee7decbe7a629e63fb2f8408
  wandb_project: fedml
  wandb_name: fedml_tf_brain_tumor_segmentation