common_args:
  training_type: "simulation"
  random_seed: 0
  scenario: "horizontal"
  using_mlops: false
  config_version: release

data_args:
  dataset: "coco128"
  data_cache_dir: "~/fedcv_data/coco128"
  partition_method: "homo"
  partition_alpha: 0.5

model_args:
  model: "unet"
  class_num: 80
  backbone: resnet
  backbone_pretrained: true
  backbone_freezed: false
  extract_feat: true
  outstride: 16
  sync_bn: true
  lr_scheduler: cos

train_args:
  federated_optimizer: "FedAvg"
  client_num_in_total: 1
  client_num_per_round: 1
  comm_round: 10
  epochs: 1
  batch_size: 1
  client_optimizer: sgd
  lr: 0.03
  momentum: 0.9
  nesterov: true
  weight_decay: 0.001
  loss_type: "ce"

validation_args:
  frequency_of_the_test: 1

device_args:
  worker_num: 4
  using_gpu: false
  gpu_mapping_file: config/gpu_mapping.yaml
  gpu_mapping_key: mapping_default

comm_args:
  backend: "MPI"
  is_mobile: 0

tracking_args:
  log_file_dir: ./log
  enable_wandb: false
  wandb_key: ee0b5f53d949c84cee7decbe7a629e63fb2f8408
  wandb_project: fedml
  wandb_name: fedml_torch_image_segmentation
