workspace: "."
entry_point: "main_entry.py"

auto_detect_public_ip: true
server_external_port: 10007
server_internal_port: 10008

bootstrap: |
  echo "Bootstrap start..."
  pip install -U fedml
  sh ./config/bootstrap.sh
  echo "Bootstrap finished"
