# Local directory where your source code resides.
# It should be the relative path to this job yaml file or the absolute path.
# If your job doesn't contain any source code, it can be empty.
workspace: train_job

# Docker image name.
# It should be the full name of the image with tag.
# If you want to use the default image, it can be empty.
docker:
  image: fedml/fedml-default-launch:cu12.1-u22.04

# Running entry commands which will be executed as the job entry point.
# Support multiple lines, which can not be empty.
job: |
  echo "Hello, Here is the FedML Nexus AI platform."
  echo "Current directory is as follows."
  pwd
  python3 main_entry.py

job_type: train              # options: train, deploy, federate

# Bootstrap shell commands which will be executed before running entry commands.
# Support multiple lines, which can be empty.
bootstrap: |
  pip install PyYAML==5.3.1 -i https://pypi.org/simple
  pip install fedml==0.8.29
  pip install -U typing_extensions -i https://pypi.org/simple
  pip install -U pydantic
  pip install -U fastapi
  echo "Bootstrap finished."

computing:
  #resource_type: RTX-4090    # e.g., A100-80G, please check the resource type list by "fedml show-resource-type" or visiting URL: https://open.fedml.ai/accelerator_resource_type
  resource_type: A100-80GB-SXM
  minimum_num_gpus: 1             # minimum # of GPUs to provision
  maximum_cost_per_hour: $10    # max cost per hour of all machines for your job
  # device_type: GPU # GPU or CPU
