entry_config:
  entry_file: fedml/torch_server.py
  conf_file: config/fedml_config.yaml
dynamic_args:
  rank: 0
  run_id: ${FEDSYS.RUN_ID}
  data_cache_dir: ${FEDSYS.PRIVATE_LOCAL_DATA}
  mqtt_config_path: /fedml/conf/mqtt_config.yaml
  s3_config_path: /fedml/conf/s3_config.yaml
  log_file_dir: /fedml/data
  log_server_url: ${FEDSYS.LOG_SERVER_URL}
  client_id_list: ${FEDSYS.CLIENT_ID_LIST}
  client_objects: ${FEDSYS.CLIENT_OBJECT_LIST}
  is_using_local_data: ${FEDSYS.IS_USING_LOCAL_DATA}
  synthetic_data_url: ${FEDSYS.SYNTHETIC_DATA_URL}
  client_num_in_total: ${FEDSYS.CLIENT_NUM}
