
class ModuleConstants:
    PLATFORM_NAME_LAUNCH = "launch"
    FEDML_CONFIG_YAML_FILE = "fedml_config.yaml"
    TRAIN_BUILD_PACKAGE_CLIENT_TYPE = "client"
    TRAIN_BUILD_PACKAGE_SERVER_TYPE = "server"

    TRAIN_BUILD_DEFAULT_DEST_DIR_NAME = "fedml-train-packages"
    FEDERATE_BUILD_DEFAULT_DEST_DIR_NAME = "fedml-federate-packages"
    ENV_FEDML_INFER_HOST = "FEDML_INFER_HOST"
    ENV_FEDML_INFER_REDIS_ADDR = "FEDML_INFER_REDIS_ADDR"
    ENV_FEDML_INFER_REDIS_PORT = "FEDML_INFER_REDIS_PORT"
    ENV_FEDML_INFER_REDIS_PASSWORD = "FEDML_INFER_REDIS_PASSWORD"
