# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_stream_comm_manager.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1egrpc_stream_comm_manager.proto\"#\n\x0e\x43onnectRequest\x12\x11\n\tclient_id\x18\x01 \x01(\x05\"1\n\x0b\x43ommRequest\x12\x11\n\tclient_id\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\x0c\"\x07\n\x05\x45mpty2i\n\x15GRPCStreamCommManager\x12*\n\x07\x43onnect\x12\x0f.ConnectRequest\x1a\x0c.CommRequest0\x01\x12$\n\x0cSendToServer\x12\x0c.CommRequest\x1a\x06.Emptyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_stream_comm_manager_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONNECTREQUEST._serialized_start=34
  _CONNECTREQUEST._serialized_end=69
  _COMMREQUEST._serialized_start=71
  _COMMREQUEST._serialized_end=120
  _EMPTY._serialized_start=122
  _EMPTY._serialized_end=129
  _GRPCSTREAMCOMMMANAGER._serialized_start=131
  _GRPCSTREAMCOMMMANAGER._serialized_end=236
# @@protoc_insertion_point(module_scope)
