#!/bin/bash

ARCH=x86_64
OS=ubuntu20.04
DISTRO=ubuntu2004
PYTHON_VERSION=3
PYTORCH_VERSION=1.11.0
NCCL_VERSION=2.11.4
CUDA_VERSION=11.4

cd ./docker/
bash build-docker.sh $ARCH $OS $DISTRO $PYTHON_VERSION $PYTORCH_VERSION $NCCL_VERSION $CUDA_VERSION
