#!/bin/bash

FEDML_MODEL_PREMISE_MASTER_PACKAGE=$1
FEDML_MODEL_OPS_VERSION=$2
DEPLOY_NAMESPACE=$3
FEDML_MODEL_OPS_ACCOUNT_ID=$4

helm package $FEDML_MODEL_PREMISE_MASTER_PACKAGE
helm install -n $DEPLOY_NAMESPACE --set env.fedmlAccountId="$FEDML_MODEL_OPS_ACCOUNT_ID" --set env.fedmlVersion=$FEDML_MODEL_OPS_VERSION $FEDML_MODEL_PREMISE_MASTER_PACKAGE ./$FEDML_MODEL_PREMISE_MASTER_PACKAGE.tar.gz
