workspace: "./src"

inference_image_name: "raphaeljin/fedml"
enable_custom_image: true

bootstrap: |
  echo "Bootstrap start..."
  pwd
  ls -l
  echo "Check shell script"
  cat fedml-deploy-bootstrap-entry-auto-gen.sh
  echo "Check main script"
  cat serve_main.py  
  echo "Bootstrap finished"

## Simulate a successful deployment
#job: |
#  python3 serve_main.py

# Then during update, simulate a failed deployment
job: |
  echo "Simulate a failed deployment"
  exit 1

auto_detect_public_ip: true
use_gpu: true