# fedml/fedml:github-actions-ubuntu-20.04
# https://github.com/FedML-AI/FedML/settings/actions/runners/new

FROM ubuntu:20.04


WORKDIR /home/github

RUN apt-get update
RUN apt install sudo
RUN sudo chmod 777 /home/github

RUN sudo apt install -y curl
RUN useradd -u 8877 github

RUN sudo ln -s /usr/bin/sha1sum /usr/bin/shasum

RUN apt install wget
RUN wget http://ftp.us.debian.org/debian/pool/main/i/icu/libicu57_57.1-6+deb9u4_amd64.deb
RUN sudo dpkg -i libicu57_57.1-6+deb9u4_amd64.deb
RUN sudo apt install dotnet-sd

USER github



# Create a folder
RUN cd /home/github && mkdir actions-runner && cd actions-runner && \
curl -o actions-runner-linux-x64-2.293.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.293.0/actions-runner-linux-x64-2.293.0.tar.gz && \
tar xzf ./actions-runner-linux-x64-2.293.0.tar.gz

# Optional: Validate the hash
# RUN echo "06d62d551b686239a47d73e99a557d87e0e4fa62bdddcf1d74d4e6b2521f8c10  actions-runner-linux-x64-2.293.0.tar.gz" | shasum -a 256 -c

ENV USER github

