class ClientConstants {
}
ClientConstants.MSG_MLOPS_CLIENT_STATUS_OFFLINE = 'OFFLINE'
ClientConstants.MSG_MLOPS_CLIENT_STATUS_IDLE = 'IDLE'
ClientConstants.MSG_MLOPS_CLIENT_STATUS_UPGRADING = 'UPGRADING'
ClientConstants.MSG_MLOPS_CLIENT_STATUS_QUEUED = 'QUEUED'
ClientConstants.MSG_MLOPS_CLIENT_STATUS_INITIALIZING = 'INITIALIZING'
ClientConstants.MSG_MLOPS_CLIENT_STATUS_TRAINING = 'TRAINING'
ClientConstants.MSG_MLOPS_CLIENT_STATUS_FAILED = 'FAILED'
ClientConstants.MSG_MLOPS_CLIENT_STATUS_FINISHED = 'FINISHED'
ClientConstants.MSG_MLOPS_SERVER_DEVICE_STATUS_OFFLINE = 'OFFLINE'
ClientConstants.MSG_MLOPS_SERVER_DEVICE_STATUS_IDLE = 'IDLE'
ClientConstants.MSG_MLOPS_SERVER_DEVICE_STATUS_STARTING = 'STARTING'
ClientConstants.MSG_MLOPS_SERVER_DEVICE_STATUS_RUNNING = 'RUNNING'
ClientConstants.MSG_MLOPS_SERVER_DEVICE_STATUS_FAILED = 'FAILED'
ClientConstants.MSG_MLOPS_SERVER_DEVICE_STATUS_FINISHED = 'FINISHED'
ClientConstants.LOCAL_HOME_RUNNER_DIR_NAME = 'fedml-client'
ClientConstants.LOCAL_RUNNER_INFO_DIR_NAME = 'runner_infos'
ClientConstants.LOCAL_PACKAGE_HOME_DIR_NAME = 'fedml_packages'
ClientConstants.FEDML_OTA_CMD_UPGRADE = 'upgrade'
ClientConstants.FEDML_OTA_CMD_RESTART = 'restart'
ClientConstants.LOGIN_MODE_CLIEN_INDEX = 0
ClientConstants.LOGIN_MODE_EDGE_SIMULATOR_INDEX = 1
ClientConstants.login_role_list = ['client', 'edge_simulator']
export { ClientConstants }
