dist_training_args:
  n_node_in_silo: 2
  n_proc_per_node: 1
  node_addresses: [172.31.25.57, 172.31.28.254]
  master_address: '172.31.25.57'
  launcher_rdzv_port: 29410


device_args:
  using_gpu: true
  gpu_mapping_file: config/gpu_mapping.yaml
  gpu_mapping_key: mapping_silo_1
