dist_training_args:
  n_node_in_silo: 2
  n_proc_per_node: 1
  node_addresses: [172.31.18.237, 172.31.17.27]
  pg_master_address: '172.31.18.237'
  pg_master_port: 29401


device_args:
  using_gpu: true
  gpu_mapping_file: config/gpu_mapping.yaml
  gpu_mapping_key: mapping_silo_1
