apiVersion: v1
kind: Service
metadata:
  name: $FEDML_AGGREGATOR_SVC
  namespace: fedml-devops-aggregator-$FEDML_AGGREGATOR_VERSION
  labels:
    app: fedml-aggregator
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: fedml-aggregator
