common_args:
  training_type: "simulation"
  random_seed: 0
  config_version: "release"
  mlops_api_key: f5b88f5dca344e6faf17809139b89c48
  mlops_project_name: sp_fedavg_test
  mlops_run_name: fedml_torch_fedavg_mnist_lr_mlsys

data_args:
  dataset: "mnist"
  data_cache_dir: ../../data
  partition_method: "hetero"
  partition_alpha: 0.5

model_args:
  model: "lr"

train_args:
  federated_optimizer: "FedAvg"
  client_id_list: "[]"
  client_num_in_total: 10
  client_num_per_round: 5
  comm_round: 10
  epochs: 1
  batch_size: 10
  client_optimizer: sgd
  learning_rate: 0.03
  weight_decay: 0.001

validation_args:
  frequency_of_the_test: 1

device_args:
  using_gpu: false
  gpu_id: 0

comm_args:
  backend: "sp"

tracking_args:
  enable_tracking: false
   # When running on MLOps platform(open.fedml.ai), the default log path is at ~/fedml-client/fedml/logs/ and ~/fedml-server/fedml/logs/
  enable_wandb: false
  wandb_key: ee0b5f53d949c84cee7decbe7a629e63fb2f8408
  wandb_entity: fedml-ai
  wandb_project: simulation
  run_name: fedml_torch_fedavg_mnist_lr
  using_mlops: false

dp_args:
  enable_dp: true
  stop_training_at_epsilon: false
  dp_solution_type: cdp # cdp or ldp
  epsilon: 0.5
  delta: 0.1
  sensitivity: 1
  mechanism_type: gaussian
  noise_multiplier: 10.0
  clipping_norm: 0.04 # float('inf') or None to deactivate
