

# FedML data
FEDML_DATA_CACHE_FOLDER = "fedml_data"
FEDML_DATA_MNIST_URL = "https://fedcv.s3.us-west-1.amazonaws.com/MNIST.zip"


# FedML Algorithm
FedML_FEDERATED_OPTIMIZER_BASE_FRAMEWORK = "base_framework"
FedML_FEDERATED_OPTIMIZER_FEDAVG = "fedavg"
FedML_FEDERATED_OPTIMIZER_FEDOPT = "fedopt"
FedML_FEDERATED_OPTIMIZER_FEDPROX = "fedprox"
FedML_FEDERATED_OPTIMIZER_CLASSICAL_VFL = "classical_vertical"
FedML_FEDERATED_OPTIMIZER_SPLIT_NN = "split_nn"
FedML_FEDERATED_OPTIMIZER_DECENTRALIZED_FL = "decentralized_fl"
FedML_FEDERATED_OPTIMIZER_FEDGAN = "fedgan"
FedML_FEDERATED_OPTIMIZER_FEDAVG_ROBUST = "fedavg_robust"
FedML_FEDERATED_OPTIMIZER_FEDGKT = "fedgkt"
FedML_FEDERATED_OPTIMIZER_FEDNAS = "fednas"
FedML_FEDERATED_OPTIMIZER_FEDSEG = "fedseg"
FedML_FEDERATED_OPTIMIZER_TURBO_AGGREGATE = "turboa_ggregate"

