# FedML TRAINING PLATFORM
FEDML_TRAINING_PLATFORM_SIMULATION = "simulation"
FEDML_TRAINING_PLATFORM_CROSS_SILO = "cross_silo"
FEDML_TRAINING_PLATFORM_CROSS_DEVICE = "cross_device"
FEDML_TRAINING_PLATFORM_DISTRIBUTED = "distributed"

# FedML TRAINING PLATFORM TYPE
FEDML_TRAINING_PLATFORM_CROSS_SILO_TYPE = 1
FEDML_TRAINING_PLATFORM_SIMULATION_TYPE = 2
FEDML_TRAINING_PLATFORM_DISTRIBUTED_TYPE = 3
FEDML_TRAINING_PLATFORM_CROSS_DEVICE_TYPE = 4

# FedML CROSS-SILO SCENARIO
FEDML_CROSS_SILO_SCENARIO_HORIZONTAL = "horizontal"
FEDML_CROSS_SILO_SCENARIO_HIERARCHICAL = "hierarchical"

# FedML SIMULATION TYPE
FEDML_SIMULATION_TYPE_SP = "sp"
FEDML_SIMULATION_TYPE_MPI = "MPI"
FEDML_SIMULATION_TYPE_NCCL = "NCCL"

# FedML data
FEDML_DATA_CACHE_FOLDER = "fedml_data"
FEDML_DATA_MNIST_URL = "https://fedcv.s3.us-west-1.amazonaws.com/MNIST.zip"


# FedML Algorithm
FEDML_FEDERATED_OPTIMIZER_BASE_FRAMEWORK = "base_framework"
FEDML_FEDERATED_OPTIMIZER_FEDAVG = "FedAvg"
FEDML_FEDERATED_OPTIMIZER_FEDOPT = "FedOpt"
FEDML_FEDERATED_OPTIMIZER_FEDPROX = "FedProx"
FEDML_FEDERATED_OPTIMIZER_CLASSICAL_VFL = "classical_vertical"
FEDML_FEDERATED_OPTIMIZER_SPLIT_NN = "split_nn"
FEDML_FEDERATED_OPTIMIZER_DECENTRALIZED_FL = "decentralized_fl"
FEDML_FEDERATED_OPTIMIZER_FEDGAN = "FedGAN"
FEDML_FEDERATED_OPTIMIZER_FEDAVG_ROBUST = "FedAvg_robust"
FEDML_FEDERATED_OPTIMIZER_FEDAVG_SEQ = "FedAvg_seq"
FEDML_FEDERATED_OPTIMIZER_FEDOPT_SEQ = "FedOpt_seq"
FEDML_FEDERATED_OPTIMIZER_FEDGKT = "FedGKT"
FEDML_FEDERATED_OPTIMIZER_FEDNAS = "FedNAS"
FEDML_FEDERATED_OPTIMIZER_FEDSEG = "FedSeg"
FEDML_FEDERATED_OPTIMIZER_TURBO_AGGREGATE = "turbo_aggregate"
FEDML_FEDERATED_OPTIMIZER_FEDNOVA = "FedNova"
FEDML_FEDERATED_OPTIMIZER_HIERACHICAL_FL = "HierarchicalFL"
FEDML_FEDERATED_OPTIMIZER_FEDSGD = "FedSGD"
FEDML_FEDERATED_OPTIMIZER_ASYNC_FEDAVG = "Async_FedAvg"




