common_args:
  training_type: "simulation"
  random_seed: 0

data_args:
  dataset: "mnist"
  data_cache_dir: "../../../data/mnist"
  partition_method: "hetero"
  partition_alpha: 0.5

model_args:
  model: "resnet18"
  group_norm_channels: 32


train_args:
  # federated_optimizer: "FedAvg_seq"
  federated_optimizer: "FedOpt"
  aggregate_seq: True
  hierarchical_agg: True
  client_id_list: "[]"
  client_num_in_total: 1000
  client_num_per_round: 4
  comm_round: 50
  epochs: 1
  batch_size: 10
  client_optimizer: sgd
  learning_rate: 0.03
  weight_decay: 0.001
  momentum: 0.0
  lr_schedule: None
  lr_step_size: 1
  lr_milestones: [1000, 2000, 3000]
  lr_decay_rate: 0.1
  nesterov: False
  server_optimizer: sgd
  server_lr: 1.0
  wd: 0.0001
  ci: 0
  server_momentum: 0.9

fedprox_args:
  fedprox_mu: 0.1


fednova_args:
  gmf: 0.0
  mu: 0.0
  dampening: 0.0

feddyn_args:
  feddyn_alpha: 1.0


validation_args:
  frequency_of_the_test: 5

device_args:
  worker_num: 4
  using_gpu: false
  gpu_mapping_file: config/gpu_mapping.yaml
  gpu_mapping_key: mapping_default
  gpu_util_parse: "localhost:2,1,1,1"


comm_args:
  backend: "MPI"
  is_mobile: 0

cache_args:
  # client_cache: "stateful"  #  localhost
  local_cache: False  # Some algorithms need to cache status, including SCAFFOLD, Feddyn 
  client_cache: "localhost"  #  localhost
  local_cache_root: "/home/comp/20481896/zhtang_FedML/local_caches"
  delete_cache: True      # Set true to delete local cache after training


tracking_args:
  # the default log path is at ~/fedml-client/fedml/logs/ and ~/fedml-server/fedml/logs/
  enable_wandb: false
  wandb_key: ee0b5f53d949c84cee7decbe7a629e63fb2f8408
  wandb_project: fedml
  wandb_name: fedml_torch_fedavg_mnist_lr
  run_name: fedml_schedule_bench
  wandb_only_server: True
  using_mlops: False
  simulation_schedule: "LinearFit-DP"
  # runtime_est_mode: "time_window" # EMA
  simulation_gpu_hetero: null    # ratio
  gpu_hetero_ratio: 1.0
  simulation_environment_hetero: null  # cos
  environment_hetero_ratio: 1.0
  tracking_runtime: False
  tag: "debug"
  exp_name: "ready"
  device_tag: "lambda3"

attack_args:
  enable_attack: false
  attack_type: None

defense_args:
  enable_defense: False
  defense_type: norm_diff_clipping
  norm_bound: 5.0
