common_args:
  training_type: "simulation"
  random_seed: 0

data_args:
  dataset: "fed_cifar100"
  data_cache_dir: "/home/chaoyanghe/zhtang_FedML/python/fedml/data/fed_cifar100/datasets"
  partition_method: "hetero"
  partition_alpha: 0.1

model_args:
  model: "lr"

train_args:
  federated_optimizer: "FedAvg_seq"
  client_id_list: "[]"
  client_num_in_total: 100
  client_num_per_round: 10
  comm_round: 4000
  epochs: 1
  batch_size: 50
  client_optimizer: sgd
  learning_rate: 0.1
  weight_decay: 0.0001

validation_args:
  frequency_of_the_test: 5

device_args:
  worker_num: 4
  using_gpu: false
  gpu_mapping_file: config/gpu_mapping.yaml
  gpu_mapping_key: mapping_default
  gpu_util_parse: "localhost:2,1,1,1,1,1,1,1"

comm_args:
  backend: "MPI"
  is_mobile: 0


tracking_args:
  log_file_dir: ./log
  enable_wandb: false
  wandb_key: ee0b5f53d949c84cee7decbe7a629e63fb2f8408
  wandb_project: fedml
  wandb_name: fedml_torch_fedavg
  using_mlops: false

attack_args:
  enable_attack: false
  attack_type: None

defense_args:
  enable_defense: true
  defense_type: norm_diff_clipping
  norm_bound: 5.0
