common_args:
  training_type: "simulation"
  random_seed: 0

data_args:
  dataset: "stackoverflow_nwp"
  data_cache_dir: "/home/chaoyanghe/fedml_data/stackoverflow"
  partition_method: "hetero"
  partition_alpha: 0.5

model_args:
  # model: "cnn"
  model: "rnn"  #  resnet18


train_args:
  federated_optimizer: "FedAvg_seq"
  client_id_list: "[]"
  client_num_in_total: 3400
  client_num_per_round: 100
  comm_round: 200
  epochs: 5
  batch_size: 20
  client_optimizer: sgd
  learning_rate: 0.03
  weight_decay: 0.0005
  lr_schedule: None


validation_args:
  frequency_of_the_test: 10

device_args:
  worker_num: 8
  using_gpu: false
  gpu_mapping_file: config/gpu_mapping.yaml
  gpu_mapping_key: mapping_default
  gpu_util_parse: "localhost:2,1,1,1,1,1,1,1"

comm_args:
  backend: "MPI"
  is_mobile: 0


tracking_args:
  log_file_dir: ./log
  enable_wandb: True
  wandb_entity: automl
  wandb_key: ee0b5f53d949c84cee7decbe7a629e63fb2f8408
  wandb_project: bench_optim
  wandb_name: fedml_optim_bench
  run_name: fedml_schedule_bench
  wandb_only_server: True
  using_mlops: False
  simulation_schedule: "LinearFit-DP"
  runtime_est_mode: "time_window" # EMA
  # simulation_gpu_hetero: "ratio"
  # gpu_hetero_ratio: 1.0

attack_args:
  enable_attack: false
  attack_type: None

defense_args:
  enable_defense: False
  defense_type: norm_diff_clipping
  norm_bound: 5.0




