common_args:
  training_type: "simulation"
  random_seed: 0
  

data_args:
  dataset: "ciao"
  data_cache_dir: "./data"
  partition_method: "hetero"
  partition_alpha: 0.5
  ego_number: 10
  hop_number: 2


model_args:
  model: "gat"
  hidden_size: 32
  node_embedding_dim: 32
  graph_embedding_dim: 64
  readout_hidden_dim: 64
  n_layers: 5
  alpha: 0.2
  num_heads: 2
  dropout: 0.3
  normalize_features: False
  normalize_adjacency: False
  sparse_adjacency: False

train_args:
  federated_optimizer: "FedOpt"
  client_id_list: "[]"
  client_num_in_total: 10
  client_num_per_round: 10
  comm_round: 100
  epochs: 5
  batch_size: 64
  metric: "prc-auc"
  client_optimizer: AdamW
  learning_rate: 0.001
  weight_decay: 0.001
  server_optimizer: sgd
  server_lr: 0.001
  wd: 0.001
  ci: 0
  server_momentum: 0.9
validation_args:
  frequency_of_the_test: 5

environment_args:
  bootstrap: config_fedopt/bootstrap.sh

device_args:
  worker_num: 4
  using_gpu: true
  gpu_mapping_file: config_fedopt/gpu_mapping.yaml
  gpu_mapping_key: mapping_default

comm_args:
  backend: "MPI"
  is_mobile: 0
  


tracking_args:
  log_file_dir: ./log
  enable_wandb: false
  wandb_key: ee0b5f53d949c84cee7decbe7a629e63fb2f8408
  wandb_project: fedml
  wandb_name: fed_node_classification