
class ApiConstants:
    RESOURCE_MATCHED_STATUS_MATCHED = "MATCHED"
    RESOURCE_MATCHED_STATUS_JOB_URL_ERROR = "ERROR_JOB_URL"
    RESOURCE_MATCHED_STATUS_INVALID_PARAMS = "INVALID_PARAMS"
    RESOURCE_MATCHED_STATUS_BLOCKED = "BLOCKED"
    RESOURCE_MATCHED_STATUS_QUEUED = "QUEUED"
    RESOURCE_MATCHED_STATUS_QUEUE_CANCELED = "QUEUE_CANCELED"
    RESOURCE_MATCHED_STATUS_BIND_CREDIT_CARD_FIRST = "BIND_CREDIT_CARD_FIRST"
    RESOURCE_MATCHED_STATUS_QUERY_CREDIT_CARD_BINDING_STATUS_FAILED = "QUERY_CREDIT_CARD_BINDING_STATUS_FAILED"
    RESOURCE_MATCHED_STATUS_NO_RESOURCES = "NO_RESOURCES"
    RESOURCE_MATCHED_STATUS_REQUEST_FAILED = "REQUEST_FAILED"

    LAUNCH_JOB_STATUS_REQUEST_FAILED = "LAUNCH_REQUEST_FAILED"
    LAUNCH_JOB_STATUS_JOB_URL_ERROR = "LAUNCH_ERROR_JOB_URL"
    LAUNCH_JOB_STATUS_JOB_CANCELED = "LAUNCH_ERROR_JOB_CANCELED"
    LAUNCH_JOB_STATUS_NO_JOBS = "LAUNCH_ERROR_NO_JOBS"

    ERROR_CODE = {RESOURCE_MATCHED_STATUS_MATCHED: 1, RESOURCE_MATCHED_STATUS_JOB_URL_ERROR: 2,
                  RESOURCE_MATCHED_STATUS_INVALID_PARAMS: 3, RESOURCE_MATCHED_STATUS_BLOCKED: 4,
                  RESOURCE_MATCHED_STATUS_QUEUED: 5, RESOURCE_MATCHED_STATUS_BIND_CREDIT_CARD_FIRST: 6,
                  RESOURCE_MATCHED_STATUS_QUERY_CREDIT_CARD_BINDING_STATUS_FAILED: 7,
                  RESOURCE_MATCHED_STATUS_NO_RESOURCES: 8, RESOURCE_MATCHED_STATUS_REQUEST_FAILED: 9,
                  LAUNCH_JOB_STATUS_REQUEST_FAILED: 10, LAUNCH_JOB_STATUS_JOB_URL_ERROR: 11,
                  LAUNCH_JOB_STATUS_JOB_CANCELED: 12, LAUNCH_JOB_STATUS_NO_JOBS: 13,
                  RESOURCE_MATCHED_STATUS_QUEUE_CANCELED: 14}
