{
  "platform": "onnxruntime",
  "max_batch_size": 1,
  "input_size": [[1,24], [1,2]],
  "input_types": ["int", "float"],
  "input": [
    {
      "name": "input",
      "data_type": "TYPE_FP32",
      "dims": []
    }
  ],
  "output": [
    {
      "name": "output",
      "data_type": "TYPE_FP32",
      "dims": []
    }
  ]
}