
common_args:
  training_type: "cross_silo"
  scenario: "horizontal"
  using_mlops: false
  random_seed: 100
  config_version: release

environment_args:
  bootstrap: config/bootstrap.sh

data_args:
  dataset: "shakespeare"
  data_cache_dir: ~/.cache/fedml_data
  partition_method: "hetero"
  partition_alpha: 0.5

model_args:
  model: "rnn"

train_args:
  federated_optimizer: "FedAvg"
  client_id_list:
  client_num_in_total: 10
  client_num_per_round: 10
  comm_round: 100
  epochs: 1
  batch_size: 32
  client_optimizer: sgd
  learning_rate: 0.03
  weight_decay: 0.001
  server_optimizer: sgd
  lr: 0.001
  server_lr: 0.001
  wd: 0.001
  ci: 0
  server_momentum: 0.9

validation_args:
  frequency_of_the_test: 1

device_args:
  worker_num: 10
  using_gpu: true
  gpu_mapping_file: config/gpu_mapping.yaml
  gpu_mapping_key: mapping_default

comm_args:
  backend: "MPI"

tracking_args:
   # When running on MLOps platform(open.fedml.ai), the default log path is at ~/.fedml/fedml-client/fedml/logs/ and ~/.fedml/fedml-server/fedml/logs/
  enable_wandb: false
  wandb_key: bf0149e33cec3bcb7833c43aa5bd6e74f9dbedaf
  wandb_project: FedmlSecurity
  wandb_name: heterp_nlp_byzantine_random_1adv


attack_args:
  enable_attack: true
  attack_type: byzantine
  byzantine_client_num: 1
  attack_mode: random

defense_args:
  enable_defense: true
  defense_type: foolsgold
