common_args:
  training_type: "cross_silo"
  random_seed: 0

data_args:
  dataset: "twitter"
  data_cache_dir: ~/.cache/fedml_data

train_args:
  client_num_in_total: 2
  client_num_per_round: 2
  comm_round: 10
  fa_task: "intersection" # intersection or cardinality

comm_args:
  backend: "MQTT_S3"

