comm_args:
  backend: MQTT_S3
  mqtt_config_path: config/mqtt_config.yaml
  s3_config_path: config/s3_config.yaml
common_args:
  random_seed: 0
  scenario: horizontal
  training_type: cross_silo
  using_mlops: false
data_args:
  data_cache_dir: ~/fedml_data
  dataset: mnist
  partition_alpha: 0.5
  partition_method: hetero
device_args:
  gpu_mapping_file: config/gpu_mapping.yaml
  gpu_mapping_key: mapping_default
  using_gpu: false
  worker_num: 2
environment_args:
  bootstrap: config/bootstrap.sh
fedml_data_args:
  dataset_name: mnist
  dataset_path: /Users/alexliang/fedml_data
  dataset_type: csv
fedml_entry_args:
  arg_items: -m $FEDML_MODEL_NAME -mc $FEDML_MODEL_CACHE_PATH -mi $FEDML_MODEL_INPUT_DIM
    -mo $FEDML_MODEL_OUTPUT_DIM -dn $FEDML_DATASET_NAME -dt $FEDML_DATASET_TYPE -dp
    $FEDML_DATASET_PATH
fedml_model_args:
  input_dim: '784'
  model_cache_path: /Users/alexliang/fedml_models
  model_name: lr
  output_dim: '10'
model_args:
  global_model_file_path: ./model_file_cache/global_model.pt
  model: lr
  model_file_cache_folder: ./model_file_cache
tracking_args:
  enable_wandb: false
  wandb_key: ee0b5f53d949c84cee7decbe7a629e63fb2f8408
  wandb_name: fedml_torch_fedavg_mnist_lr
  wandb_project: fedml
train_args:
  batch_size: 10
  client_id_list: null
  client_num_in_total: 2
  client_num_per_round: 2
  client_optimizer: sgd
  comm_round: 3
  epochs: 1
  federated_optimizer: FedAvg
  learning_rate: 0.03
  weight_decay: 0.001
validation_args:
  frequency_of_the_test: 1
