comm_args:
  backend: MQTT_S3
  mqtt_config_path: config/mqtt_config.yaml
  s3_config_path: config/s3_config.yaml
common_args:
  random_seed: 0
  scenario: horizontal
  training_type: cross_silo
  using_mlops: false
data_args:
  data_cache_dir: ~/.cache/fedml_data
  dataset: mnist
  partition_alpha: 0.5
  partition_method: hetero
device_args:
  gpu_mapping_file: config/gpu_mapping.yaml
  gpu_mapping_key: mapping_default
  using_gpu: false
  worker_num: 2
environment_args:
  bootstrap: config/bootstrap.sh
model_args:
  global_model_file_path: ./model_file_cache/global_model.pt
  model: lr
  model_file_cache_folder: ./model_file_cache
tracking_args:
  enable_wandb: false
  wandb_key: ee0b5f53d949c84cee7decbe7a629e63fb2f8408
  wandb_name: fedml_torch_fedavg_mnist_lr
  wandb_project: fedml
train_args:
  batch_size: 10
  client_id_list: null
  client_num_in_total: 2
  client_num_per_round: 2
  client_optimizer: sgd
  comm_round: 3
  epochs: 1
  federated_optimizer: FedAvg
  learning_rate: 0.03
  weight_decay: 0.001
validation_args:
  frequency_of_the_test: 1
