common_args:
  training_type: "simulation"
  random_seed: 0

data_args:
  dataset: "cifar10"
  data_cache_dir: ~/fedml_data
  partition_method: "hetero"
  partition_alpha: 0.5

model_args:
  model: "darts"

train_args:
  federated_optimizer: "FedNAS"
  client_id_list: "[]"
  client_num_in_total: 4
  client_num_per_round: 4
  comm_round: 3
  epochs: 1
  batch_size: 50
  client_optimizer: sgd
  weight_decay: 0.001
  server_optimizer: sgd
  lr: 0.001
  server_lr: 0.001
  wd: 0.001
  ci: 0
  server_momentum: 0.9
  init_channels: 16
  layers: 8
  auxiliary: false
  momentum: 0.9
  arch_learning_rate: 0.0003
  arch_weight_decay: 0.001
  learning_rate_min: 0.001
  learning_rate: 0.025
  lambda_train_regularizer: 1
  lambda_valid_regularizer: 1
  grad_clip: 5
  tau_max: 10
  tau_min: 1
  report_freq: 1



validation_args:
  frequency_of_the_test: 5

device_args:
  worker_num: 4
  using_gpu: true
  gpu_mapping_file: config/gpu_mapping.yaml
  gpu_mapping_key: mapping_config1_5

comm_args:
  backend: "MPI"
  is_mobile: 0
  stage: 'train'


tracking_args:
   # When running on MLOps platform(open.fedml.ai), the default log path is at ~/fedml-client/fedml/logs/ and ~/fedml-server/fedml/logs/
  enable_wandb: false
  wandb_key: ee0b5f53d949c84cee7decbe7a629e63fb2f8408
  wandb_project: fedml
  wandb_name: fedml_torch_fedavg_mnist_lr
  using_mlops: false