common_args:
  training_type: "simulation"
  random_seed: 0
  scenario: "horizontal"
  using_mlops: false
  config_version: release

environment_args:
  bootstrap: config/bootstrap.sh

data_args:
  dataset: "Fed-Heart-Disease"
  data_cache_dir: ~/healthcare/heart_disease # flamby: /media/beiyu/TOSHIBA EXT/dataset/heart_disease
  partition_method: "hetero"
  partition_alpha: 0.5
  debug: false # flamby: debug or not
  preprocessed: false # flamby: preprocessed or not, need to preprocess in first
  download: true # flamby: download or not

model_args:
  model: "LR"
  input_dim: 13
  output_dim: 1

train_args:
  federated_optimizer: "FedAvg"
  client_id_list:
  client_num_in_total: 2
  client_num_per_round: 2
  comm_round: 5
  epochs: 1
  batch_size: 4
  client_optimizer: adam
  lr: 0.001
  weight_decay: 0.001

validation_args:
  frequency_of_the_test: 1

device_args:
  worker_num: 2
  using_gpu: false
  gpu_mapping_file: config/gpu_mapping.yaml
  gpu_mapping_key: mapping_default

comm_args:
  backend: "MPI"
  is_mobile: 0

tracking_args:
  log_file_dir: ./log
  enable_wandb: false
  wandb_key: ee0b5f53d949c84cee7decbe7a629e63fb2f8408
  wandb_project: fedml
  wandb_name: fedml_healthcare_kits19
