# This is a basic workflow to help you get started with Actions

name: ML-Engines-Linux

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    # Nightly build at 12:12 A.M.
    - cron: "12 12 */1 * *"
  pull_request:
    branches: [ master,  test/v0.7.0 ]
    types: [opened, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  jax-ml-engines-test:
    defaults:
      run:
        shell: bash
        working-directory: python
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        arch: [ X64 ]
        python-version: [ '3.8' ]
        client-index: [ '0', '1', '2' ]
    #        exclude:
    #          - os: macos-latest
    #            python-version: '3.8'
    #          - os: windows-latest
    #            python-version: '3.6'
    runs-on: [ self-hosted, runner-linux, devops ]
    timeout-minutes: 15
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v3
      - name: pip install -e ./
        run: |
          pip install -e ./
          pip install -e '.[jax]'

      - name: server - jax - fedavg
        run: |
          cd examples/cross_silo/jax_haiku_mqtt_s3_fedavg_mnist_lr_example
          run_id=jax-ml-engine-${{ format('{0}{1}{2}{3}', github.run_id, matrix.os, matrix.arch, matrix.python-version) }}
          echo ${run_id}
          bash run_server.sh $run_id
        if: ${{ matrix.client-index == '0' }}

      - name: client 1 - jax - fedavg
        run: |
          cd examples/cross_silo/jax_haiku_mqtt_s3_fedavg_mnist_lr_example
          run_id=jax-ml-engine-${{ format('{0}{1}{2}{3}', github.run_id, matrix.os, matrix.arch, matrix.python-version) }}
          echo ${run_id}
          bash run_client.sh 1 $run_id
        if: ${{ matrix.client-index == '1' }}

      - name: client 2 - jax - fedavg
        run: |
          cd examples/cross_silo/jax_haiku_mqtt_s3_fedavg_mnist_lr_example
          run_id=jax-ml-engine-${{ format('{0}{1}{2}{3}', github.run_id, matrix.os, matrix.arch, matrix.python-version) }}
          echo ${run_id}
          bash run_client.sh 2 $run_id
        if: ${{ matrix.client-index == '2' }}
