# This is a basic workflow to help you get started with Actions

name: CROSS-DEVICE-MNN-Linux

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    # Nightly build at 12:12 A.M.
    - cron: "12 12 */1 * *"
  pull_request:
    branches: [ master, test/v0.7.0 ]
    types: [opened, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cross-device-mnn-server:
    defaults:
      run:
        shell: bash
        working-directory: python
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        arch: [X64]
        python-version: ['3.8']
#        exclude:
#          - os: macos-latest
#            python-version: '3.8'
#          - os: windows-latest
#            python-version: '3.6'
    runs-on: [self-hosted, runner-linux, devops, mnn]
    timeout-minutes: 15
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v3
      - name: pip install -e ./
        run: |
          pip install -e ./
      - name: Install MNN
        run: |
          pip install mnn==1.1.6

      - name: test server of cross-device
        run: |
          cd quick_start/beehive
          timeout 60 bash run_server.sh || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
          
