# This is a basic workflow to help you get started with Actions

name: SMOKE TEST

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, test/v0.7.0, dev/v0.7.0 ]
  pull_request:
    branches: [ master, test/v0.7.0, dev/v0.7.0 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "mlops-cli-test"
  pip-install-fedml:
    defaults:
      run:
        shell: bash
        working-directory: python
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        arch: [X86, X64, ARM, ARM64]
        python-version: ['3.6', '3.7', '3.8', '3.9']
#        exclude:
#          - os: macos-latest
#            python-version: '3.8'
#          - os: windows-latest
#            python-version: '3.6'
    runs-on: [self-hosted]
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v3
      - name: pip install -e ./
        run: |
          pip install -e ./
      # Runs a single command using the runners shell
      - name: test "fedml login" and "fedml build"
        run: |
          cd tests/smoke_test/cli
          bash login.sh
          bash build.sh
      - name: test simulation-sp
        run: |
          cd tests/smoke_test/simulation_sp
          python main.py