# This is a basic workflow to help you get started with Actions

name: PIP, CLI, SP - On Linux

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    # Nightly build at 12:12 A.M.
    - cron: "12 12 */1 * *"
  pull_request:
    branches: [ master,  test/v0.7.0, dev/0.7.0 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: write-all

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pip-install-fedml-and-test-sp:
    defaults:
      run:
        shell: bash
        working-directory: python
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest]
        arch: [X64]
        python-version: ['3.8']
#        exclude:
#          - os: macos-latest
#            python-version: '3.8'
#          - os: windows-latest
#            python-version: '3.6'
    runs-on: [self-hosted, runner-linux, devops]
    timeout-minutes: 15
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # https://github.com/actions/checkout/issues/116#issuecomment-644419389
      - uses: actions/checkout@v3
      - name: pip install -e ./
        run: |
          pip install -e ./

      - name: test "fedml login" and "fedml build"
        run: |
          cd tests/smoke_test/cli
          bash login.sh
          bash build.sh
      - name: test simulation-sp
        run: |
          cd quick_start/parrot
          python torch_fedavg_mnist_lr_one_line_example.py --cf fedml_config.yaml
          python torch_fedavg_mnist_lr_custum_data_and_model_example.py --cf fedml_config.yaml

      - name: test sp - sp_decentralized_mnist_lr_example
        run: |
          cd examples/simulation/sp_decentralized_mnist_lr_example
          python torch_fedavg_mnist_lr_step_by_step_example.py --cf fedml_config.yaml

      - name: test sp - sp_fednova_mnist_lr_example
        run: |
          cd examples/simulation/sp_fednova_mnist_lr_example
          python torch_fednova_mnist_lr_step_by_step_example.py --cf fedml_config.yaml
          
      - name: test sp - sp_fedopt_mnist_lr_example
        run: |
          cd examples/simulation/sp_fedopt_mnist_lr_example
          python torch_fedopt_mnist_lr_step_by_step_example.py --cf fedml_config.yaml

      - name: test sp - sp_hierarchicalfl_mnist_lr_example
        run: |
          cd examples/simulation/sp_hierarchicalfl_mnist_lr_example
          python torch_hierarchicalfl_mnist_lr_step_by_step_example.py --cf fedml_config.yaml

      - name: test sp - sp_turboaggregate_mnist_lr_example
        run: |
          cd examples/simulation/sp_turboaggregate_mnist_lr_example
          python torch_turboaggregate_mnist_lr_step_by_step_example.py --cf fedml_config.yaml 

      - name: test sp - sp_vertical_mnist_lr_example
        run: |
          cd examples/simulation/sp_vertical_mnist_lr_example
          python torch_vertical_mnist_lr_step_by_step_example.py --cf fedml_config.yaml 
