name: Examples Test

on:
#  schedule:
#    # Nightly build at 12:12 A.M.
#    - cron: "12 12 */1 * *"
  push:
    branches: [ master, test/v0.7.0 ]
  pull_request:
    branches: [ master, test/v0.7.0 ]
  workflow_dispatch:

jobs:
  simulation:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false
      matrix:
        include:
          # from mpi4py import MPI
          #  ImportError: DLL load failed while importing MPI: The specified module could not be found.
          - os: windows-2019-py38-amd64
            python: 38
            bitness: 64
            platform_id: win_amd64
          # from mpi4py import MPI
          #  ImportError: DLL load failed while importing MPI: The specified module could not be found.
          - os: windows-latest-py39-amd64
            python: 39
            bitness: 64
            platform_id: win_amd64
          # ERROR: No matching distribution found for MNN==1.1.6
          - os: windows-latest-py310-amd64
            python: 310
            bitness: 64
            platform_id: win_amd64

          # auditwheel.main_repair:This does not look like a platform wheel
          - os: ubuntu-latest-py38-x86
            python: 38
            bitness: 64
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014
          # auditwheel.main_repair:This does not look like a platform wheel
          - os: ubuntu-latest-py39-x86
            python: 39
            bitness: 64
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014
          # auditwheel.main_repair:This does not look like a platform wheel
          - os: ubuntu-latest-py310-x86
            python: 310
            bitness: 64
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014

          # _configtest.c:2:10: fatal error: 'mpi.h' file not found
          - os: macos-latest-py38-x86
            bitness: 64
            python: 38
            platform_id: macosx_x86_64
          # _configtest.c:2:10: fatal error: 'mpi.h' file not found
          - os: macos-latest-py39-x86
            bitness: 64
            python: 39
            platform_id: macosx_x86_64
          # _configtest.c:2:10: fatal error: 'mpi.h' file not found
          - os: macos-latest-py310-x86
            bitness: 64
            python: 310
            platform_id: macosx_x86_64

          # MacOS arm64
          - os: macos-latest-py38-arm64
            bitness: 64
            python: 38
            platform_id: macosx_arm64
          - os: macos-latest-py39-arm64
            bitness: 64
            python: 39
            platform_id: macosx_arm64
          - os: macos-latest-py310-arm64
            bitness: 64
            python: 310
            platform_id: macosx_arm64

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: test simulation examples
        run: bash test/test_examples/test_simulation_examples.sh

  cross_silo:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: python

    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false
      matrix:
        include:
          # from mpi4py import MPI
          #  ImportError: DLL load failed while importing MPI: The specified module could not be found.
          - os: windows-2019-py38-amd64
            python: 38
            bitness: 64
            platform_id: win_amd64
          # from mpi4py import MPI
          #  ImportError: DLL load failed while importing MPI: The specified module could not be found.
          - os: windows-latest-py39-amd64
            python: 39
            bitness: 64
            platform_id: win_amd64
          # ERROR: No matching distribution found for MNN==1.1.6
          - os: windows-latest-py310-amd64
            python: 310
            bitness: 64
            platform_id: win_amd64

          # auditwheel.main_repair:This does not look like a platform wheel
          - os: ubuntu-latest-py38-x86
            python: 38
            bitness: 64
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014
          # auditwheel.main_repair:This does not look like a platform wheel
          - os: ubuntu-latest-py39-x86
            python: 39
            bitness: 64
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014
          # auditwheel.main_repair:This does not look like a platform wheel
          - os: ubuntu-latest-py310-x86
            python: 310
            bitness: 64
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014

          # _configtest.c:2:10: fatal error: 'mpi.h' file not found
          - os: macos-latest-py38-x86
            bitness: 64
            python: 38
            platform_id: macosx_x86_64
          # _configtest.c:2:10: fatal error: 'mpi.h' file not found
          - os: macos-latest-py39-x86
            bitness: 64
            python: 39
            platform_id: macosx_x86_64
          # _configtest.c:2:10: fatal error: 'mpi.h' file not found
          - os: macos-latest-py310-x86
            bitness: 64
            python: 310
            platform_id: macosx_x86_64

          # MacOS arm64
          - os: macos-latest-py38-arm64
            bitness: 64
            python: 38
            platform_id: macosx_arm64
          - os: macos-latest-py39-arm64
            bitness: 64
            python: 39
            platform_id: macosx_arm64
          - os: macos-latest-py310-arm64
            bitness: 64
            python: 310
            platform_id: macosx_arm64

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: bash test/test_examples/test_cross_silo_examples.sh

  cross_device:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: python

    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false
      matrix:
        include:
          # from mpi4py import MPI
          #  ImportError: DLL load failed while importing MPI: The specified module could not be found.
          - os: windows-2019-py38-amd64
            python: 38
            bitness: 64
            platform_id: win_amd64
          # from mpi4py import MPI
          #  ImportError: DLL load failed while importing MPI: The specified module could not be found.
          - os: windows-latest-py39-amd64
            python: 39
            bitness: 64
            platform_id: win_amd64
          # ERROR: No matching distribution found for MNN==1.1.6
          - os: windows-latest-py310-amd64
            python: 310
            bitness: 64
            platform_id: win_amd64

          # auditwheel.main_repair:This does not look like a platform wheel
          - os: ubuntu-latest-py38-x86
            python: 38
            bitness: 64
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014
          # auditwheel.main_repair:This does not look like a platform wheel
          - os: ubuntu-latest-py39-x86
            python: 39
            bitness: 64
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014
          # auditwheel.main_repair:This does not look like a platform wheel
          - os: ubuntu-latest-py310-x86
            python: 310
            bitness: 64
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014

          # _configtest.c:2:10: fatal error: 'mpi.h' file not found
          - os: macos-latest-py38-x86
            bitness: 64
            python: 38
            platform_id: macosx_x86_64
          # _configtest.c:2:10: fatal error: 'mpi.h' file not found
          - os: macos-latest-py39-x86
            bitness: 64
            python: 39
            platform_id: macosx_x86_64
          # _configtest.c:2:10: fatal error: 'mpi.h' file not found
          - os: macos-latest-py310-x86
            bitness: 64
            python: 310
            platform_id: macosx_x86_64

          # MacOS arm64
          - os: macos-latest-py38-arm64
            bitness: 64
            python: 38
            platform_id: macosx_arm64
          - os: macos-latest-py39-arm64
            bitness: 64
            python: 39
            platform_id: macosx_arm64
          - os: macos-latest-py310-arm64
            bitness: 64
            python: 310
            platform_id: macosx_arm64

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: bash test/test_examples/test_cross_device_examples.sh